package com.litongjava.jfinal.models.voidetotext.model;

import com.litongjava.jfinal.models.voidetotext.model.base.BaseRecognized;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recognized extends BaseRecognized<Recognized> {
	public static final Recognized dao = new Recognized().dao();
}

