name: Java CI with Maven and Java FX

on:
  push:
    branches: [ "master","main" ]
  pull_request:
    branches: [  "master","main" ]

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'graalvm'
          cache: maven

      - name: Install GraalVM
          run: |
            curl -L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-[graalvm-version]/graalvm-ce-java[version]-linux-amd64-[graalvm-version].tar.gz -o graalvm.tar.gz
            tar -xzf graalvm.tar.gz
            echo "$PWD/graalvm-ce-java[version]-[graalvm-version]/bin" >> $GITHUB_PATH

      - name: Configure GraalVM
        run: |
          gu install native-image

      - name: chage to project path
        run: cd maven\gui-javafx-oracle-jdk17-demo

      - name: Install maven wrapper
        run: |
          mvn -N io.takari:maven:wrapper -Dmaven=3.8.8

      - name: Build with Maven
        run: ./mvnw gluonfx:build

      - name : Show Native Files
        run : tree target
          -
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target